drop table if exists user_roles;
drop table if exists user_permissions;
drop table if exists prospect_activities;
drop table if exists efforts;
drop table if exists prospects;
drop table if exists activities;
drop table if exists statuses;
drop table if exists users;
drop table if exists roles;